import type { Metadata } from "next";
import "../globals.css";

import { Navigation } from "@/components/Navigation/Navigation";

export const metadata: Metadata = {
    title: "Mail de Calen dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Navigation>{children}</Navigation>
    );
}
